### ISSUE TITLE
No package on unpkg.

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/gcds-utility#29]
When navigating to https://unpkg.com/gcds-utility/dist/utilities.min.css you get a blank file.

**Comment by melaniebmn** [comment]
Hi @CalvinRodo,

Thank you for flagging this! We recently moved the repo into the CDS org and missed updating the link. It's updated now and should be pointing to the correct link.

Here is the correct link:
`<link rel="stylesheet" href="https://unpkg.com/@cdssnc/gcds-utility/dist/utilities.min.css">`

**Comment by melaniebmn** [comment]
Addressed in #31
